// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjmazefhgwcandderxqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbWF6ZWZoZ3djYW5kZGVyeHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTI1ODUsImV4cCI6MjA2NTIyODU4NX0.L0_b0w7hciTBxqau4771v9hbqePgbCklef2qwdZu1EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);